### PR TITLE
My Issue result

### PR DESCRIPTION
**Pull request by annapav7**
Hi @jlpalomino  I just worried about " Can’t automatically merge. Don’t worry, you can still create the pull request." message.

### CODE REVIEW

**Comment by jlpalomino** [comment]
@annapav7 No worries about this conflict - I will show everyone on Friday how these can be resolved!  Please do submit a new notebook like I explained in the CANVAS discussion response.

**Comment by jlpalomino** [comment]
@annapav7 Just a note about submitting the new notebook, you do not have to open another pull request.  All future commits will just be added to this open pull request, until I merged it on Friday morning.

**Comment by jlpalomino** [comment]
@annapav7 please leave this pull request open, unless you plan to create a new pull request.  I will merge your pull request to the main repository owned by earthlab-education on Friday morning.

**Comment by annapav7** [comment]
My issue number is #2 Add notebook about hometown for annapav7.

**Pull request merged**
