### PR TITLE
adding portland, or & boulder, co

### PR DESCRIPTION
**Pull request by shelbyross**
@lisestdenis homework 7 pull request....  this addresses #92

### CODE REVIEW

**Comment by shelbyross** [comment]
@lisestdenis homework 7 pull request.... this addresses #92.
I did not follow the directions correctly and added the files to my github as a group at the same time instead of individually. I am not sure how to redo this so the labels for the files are correct.

**Comment by lisestdenis** [comment]
Hi @shelbyross - Your file names need to be updated so that the csv files are named country-city.csv and your notebooks are renamed city-st.ipynb (e.g. portland-or.ipynb). I can help you figure out how to fix it when you have time.

**Comment by lisestdenis** [comment]
@shelbyross also, the content of your csv files are missing the first few columns. Make sure they match the specifications.

**Comment by shelbyross** [comment]
I Have updated issue #103 @lisestdenis by reuploading them to the folders.

**Pull request closed without merging**
